name: GitHub Actions Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '20 20 * * *'

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@gitlab.com:Misaka-blog/warp-script.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}
